// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirp = `-- name: GetChirp :one
SELECT id, body, user_id, created_at, updated_at FROM chirps WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
